### ISSUE TITLE
icon-iPhone20@[2|3]x exports at 150% of expected resolution

### ISSUE THREAD

**Issue by heestand-xyz** [gearnshaw/Painless-icon-generation-for-iOS-apps#1]
Hey, the pipeline works great, tho there's one error.

Here's the changes needed:
`icon-iPhone20@2x `exports at `60x60`, but should be `40x40`.
`icon-iPhone20@3x` exports at `90x90`, but should be `60x60`.

Epic repo tho!
Thanks

**Comment by ch4ot1c** [comment]
Indeed!

Backlink to the info article: https://medium.com/sketch-app-sources/painless-icon-generation-for-ios-apps-with-sketch-and-xcode-part-1-a169794aac8b

(part 3 has the easy method)

**Comment by gearnshaw** [comment]
Thanks for the bug reports. This is fixed thanks to a PR from @mc7h.
